-- FoodExpress MySQL Schema
CREATE DATABASE IF NOT EXISTS foodexpress CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE foodexpress;

CREATE TABLE IF NOT EXISTS Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(20),
  password VARCHAR(255) NOT NULL,
  role ENUM('customer','owner','admin') DEFAULT 'customer',
  avatar VARCHAR(500),
  isActive BOOLEAN DEFAULT TRUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255),
  image VARCHAR(500),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Restaurants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  address VARCHAR(500),
  image VARCHAR(500),
  cuisineType VARCHAR(100),
  deliveryTime INT DEFAULT 30,
  priceForTwo FLOAT DEFAULT 500,
  rating FLOAT DEFAULT 0,
  offer VARCHAR(255),
  featured BOOLEAN DEFAULT FALSE,
  isOpen BOOLEAN DEFAULT TRUE,
  ownerId INT,
  categoryId INT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ownerId) REFERENCES Users(id) ON DELETE SET NULL,
  FOREIGN KEY (categoryId) REFERENCES Categories(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS FoodItems (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price FLOAT NOT NULL,
  image VARCHAR(500),
  menuCategory VARCHAR(100) DEFAULT 'Main Course',
  isVeg BOOLEAN DEFAULT TRUE,
  available BOOLEAN DEFAULT TRUE,
  calories INT,
  protein FLOAT,
  carbs FLOAT,
  fat FLOAT,
  healthScore INT,
  restaurantId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (restaurantId) REFERENCES Restaurants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Addresses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  line1 VARCHAR(255),
  line2 VARCHAR(255),
  city VARCHAR(100),
  state VARCHAR(100),
  postalCode VARCHAR(20),
  isDefault BOOLEAN DEFAULT FALSE,
  userId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Carts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  items JSON DEFAULT ('[]'),
  userId INT NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  status ENUM('placed','preparing','picked','out_for_delivery','delivered','cancelled') DEFAULT 'placed',
  subtotal FLOAT DEFAULT 0,
  tax FLOAT DEFAULT 0,
  deliveryCharge FLOAT DEFAULT 40,
  total FLOAT DEFAULT 0,
  deliveryAddress VARCHAR(500),
  contactPhone VARCHAR(20),
  deliveryTimeEstimate INT,
  deliveryPartner VARCHAR(255),
  couponCode VARCHAR(50),
  discount FLOAT DEFAULT 0,
  userId INT NOT NULL,
  restaurantId INT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (restaurantId) REFERENCES Restaurants(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS OrderItems (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quantity INT DEFAULT 1,
  price FLOAT,
  orderId INT NOT NULL,
  foodItemId INT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (orderId) REFERENCES Orders(id) ON DELETE CASCADE,
  FOREIGN KEY (foodItemId) REFERENCES FoodItems(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  method VARCHAR(50),
  amount FLOAT,
  status ENUM('pending','paid','failed') DEFAULT 'pending',
  orderId INT NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (orderId) REFERENCES Orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rating INT,
  comment TEXT,
  userId INT NOT NULL,
  restaurantId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (restaurantId) REFERENCES Restaurants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Favorites (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  restaurantId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (restaurantId) REFERENCES Restaurants(id) ON DELETE CASCADE,
  UNIQUE KEY unique_favorite (userId, restaurantId)
);

CREATE TABLE IF NOT EXISTS Coupons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  discountType ENUM('percentage','flat') DEFAULT 'percentage',
  discountValue FLOAT NOT NULL,
  minOrder FLOAT DEFAULT 0,
  maxDiscount FLOAT,
  expiresAt DATETIME,
  isActive BOOLEAN DEFAULT TRUE,
  userId INT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE SET NULL
);
